### ISSUE TITLE
Off the page on mobile, Toggle 

### ISSUE THREAD

**Issue by monalisa62003** [gchoyal/HTML-Nested-Navigation-menu-with-Wide-dropdown-Menu#1]
Hey i love this, exactly what ive been looking for
Was wondering why when i have a list of names with a comma in between the page goes past the Toggle button?

Is it possible to remove the Toggle completely and just have the menu showing?

**Comment by gchoyal** [comment]
Hi @monalisa62003 , 

Add below css to always show menu in mobile 
.header .navbar-collapse.collapse {
    display: block !important;
}

But it's not a good idea to always show menu in the header, especially if the menu is sticky menu. if your using this menu in the sidebar then it's good. 

Thanks

**Comment by monalisa62003** [comment]
Which file do I put this in?
Sorry am not a great coder, learning slowly lol

**Comment by gchoyal** [comment]
css/style.css

**Comment by monalisa62003** [comment]
No change

**Comment by monalisa62003** [comment]
ignore the no change, wasnt doing it right

so i use coppermine, and i implented this at the top, but the wider menu is showing bulletpoints which just messes the menu up. any ideas how to rid of them?
